# Generated by Django 4.2.4 on 2023-08-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
