# Generated by Django 4.2.4 on 2023-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_userprofileinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(),
        ),
    ]
